server:
  port: 8081
spring:
  application.name: fooconsumer
  cloud.zookeeper:
    prefix: sample
    dependencies:
      fooprovider: ~

stubrunner:
  work-offline: true
  use-microservice-definitions: true
